services:

  mongo:
    container_name: tbdm-mongo-db
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: tbdm
      MONGO_INITDB_ROOT_PASSWORD: tbdm
  python:
    container_name: be-objdetection
    build: .
    ports:
      - 8000:8000
